# Menu settings
menu:
  starter_example:
    name: Example
    url: /lato/starter/example
    icon: example
    position: 89
    permission: 6

# Custom assets settings
assets:
  starter_application_css:
    url: lato_starter/application
    type: css
  starter_application_js:
    url: lato_starter/application
    type: js
