# Impostazione voci del menu
menu:
  starter_example:
    name: Example
    url: /lato/starter/example
    icon: example

# Impostazione assets custom
assets:
  starter_application_css:
    url: lato_starter/application
    type: css
  starter_application_js:
    url: lato_starter/application
    type: js
